
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 *
 */
public class Issues extends javax.swing.JInternalFrame {
    
    Connection conn ;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Books
     */
    public Issues() {
        
        initComponents();
        conn = JDBC.ConnectDB();
        loadTable();
        dateissue.setDateFormatString("yyyy-MM-dd");
        datedue.setDateFormatString("yyyy-MM-dd");
        
         this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI)this.getUI();
        bui.setNorthPane(null);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmemid = new javax.swing.JTextField();
        txtmemname = new javax.swing.JTextField();
        btnmemget = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblissues = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dateissue = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        datedue = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtisbn = new javax.swing.JTextField();
        btnbookget = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtbookname = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(898, 487));
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                formAncestorResized(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnadd.setText("Issue");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnadd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Member ID");

        jLabel3.setText("Member Name");

        txtmemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmemidActionPerformed(evt);
            }
        });
        txtmemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmemidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmemidKeyReleased(evt);
            }
        });

        txtmemname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmemnameActionPerformed(evt);
            }
        });

        btnmemget.setText("Get");
        btnmemget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmemgetActionPerformed(evt);
            }
        });

        jLabel1.setText("Member Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmemname)
                    .addComponent(txtmemid))
                .addGap(18, 18, 18)
                .addComponent(btnmemget)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmemid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnmemget, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmemname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setAutoscrolls(true);

        tblissues.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblissues.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblissuesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblissues);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setText("Issue Date");

        jLabel7.setText("Due Date");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(47, 47, 47)
                .addComponent(dateissue, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233)
                .addComponent(jLabel7)
                .addGap(39, 39, 39)
                .addComponent(datedue, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datedue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(dateissue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(22, 22, 22)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(21, 21, 21))))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("ISBN");

        jLabel5.setText("Book Name");

        btnbookget.setText("Get");
        btnbookget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookgetActionPerformed(evt);
            }
        });

        jLabel8.setText("Book Ddetails");

        txtbookname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbooknameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(57, 57, 57)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtbookname)
                        .addGap(1, 1, 1))
                    .addComponent(txtisbn))
                .addGap(12, 12, 12)
                .addComponent(btnbookget)
                .addGap(48, 48, 48))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbookget))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtbookname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Report");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
            
    
        String memberid = txtmemid.getText();
        String membername = txtmemname.getText();
        String isbn = txtisbn.getText();
        String bookname = txtbookname.getText();
        String issuedate = ((JTextField)dateissue.getDateEditor().getUiComponent()).getText();
        String duedate = ((JTextField)datedue.getDateEditor().getUiComponent()).getText();
        
        try{
            
            String sql = "INSERT INTO `issue`(`memberid`, `membername`, `isbn`, `bookname`, `issuedate`, `duedate`,`status`) VALUES('"+memberid+"','"+membername+"','"+isbn+"','"+bookname+"','"+issuedate+"','"+duedate+"','Issued')";            
            pst = conn.prepareStatement(sql);
            pst.execute();
            
            rs.close();
            pst.close();
            
            JOptionPane.showMessageDialog(rootPane, "Book Issued Successfully!");
            
             UpdateBooks();
             UpdateMembers();
             loadTable();
                            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(rootPane, e);
        
        }         
    }//GEN-LAST:event_btnaddActionPerformed

    private void loadTable(){
    
        try{
        
            String sql ="SELECT `issueid`, `memberid`, `membername`, `isbn`, `bookname`, `issuedate`, `duedate` , `status` FROM `issue`";
            pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblissues.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
            rs.close();
            pst.close();
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(rootPane, e);
        
        }
    }  
  
    
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try{
            
            DeletedIssues();
            
            String sql ="DELETE FROM `issue` WHERE isbn ='"+txtisbn.getText()+"' && memberid ='"+txtmemid.getText()+"'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            
            rs.close();
            pst.close();
            
            JOptionPane.showMessageDialog(rootPane, "Successfully Deleted");
            loadTable();
            
        }catch(Exception e){
        
           JOptionPane.showMessageDialog(rootPane, e);

        } 
        
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tblissuesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblissuesMouseClicked

        
        DefaultTableModel tmodel = (DefaultTableModel)tblissues.getModel();
        int selectrowindex = tblissues.getSelectedRow();
       
        
        txtmemid.setText(tmodel.getValueAt(selectrowindex, 1).toString());
        txtmemname.setText(tmodel.getValueAt(selectrowindex, 2).toString());
        txtisbn.setText(tmodel.getValueAt(selectrowindex, 3).toString());
        txtbookname.setText(tmodel.getValueAt(selectrowindex, 4).toString());
        ((JTextField)dateissue.getDateEditor().getUiComponent()).setText(tmodel.getValueAt(selectrowindex, 5).toString());
        ((JTextField)datedue.getDateEditor().getUiComponent()).setText(tmodel.getValueAt(selectrowindex, 6).toString());
   
        // TODO add your handling code here:
    }//GEN-LAST:event_tblissuesMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
      
        String memberid = txtmemid.getText();
        String membername = txtmemname.getText();
        String isbn = txtisbn.getText();
        String bookname = txtbookname.getText();
        String issuedate = ((JTextField)dateissue.getDateEditor().getUiComponent()).getText();
        String duedate = ((JTextField)datedue.getDateEditor().getUiComponent()).getText();

        
        
        try{
            
            
            String sql = "UPDATE `issue` SET `memberid`='"+memberid+"',`membername`='"+membername+"',`isbn`='"+isbn+"',`bookname`='"+bookname+"',`issuedate`='"+issuedate+"',`duedate`='"+duedate+"' WHERE isbn ='"+txtisbn.getText()+"' && memberid ='"+txtmemid.getText()+"'";
            pst =conn.prepareStatement(sql);
            pst.execute();
            
            rs.close();
            pst.close();
            
            JOptionPane.showMessageDialog(rootPane, "Successfully Updated");
            loadTable();
            
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(rootPane, e);

        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtbooknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbooknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbooknameActionPerformed

    private void txtmemidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmemidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmemidKeyReleased

    private void txtmemidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmemidKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtmemidKeyPressed

    private void txtmemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmemidActionPerformed

    private void txtmemnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmemnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmemnameActionPerformed

    private void btnmemgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmemgetActionPerformed
        // TODO add your handling code here:        
        SearchMember();
    }//GEN-LAST:event_btnmemgetActionPerformed

    private void btnbookgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookgetActionPerformed
        // TODO add your handling code here:
        
        SearchBook();
    }//GEN-LAST:event_btnbookgetActionPerformed

    private void formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorResized

       int a =  evt.getChanged().getWidth();
       int b = evt.getChanged().getHeight();
       this.setSize(a, b);
    }//GEN-LAST:event_formAncestorResized

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       LocalDate today = LocalDate.now();
        
       int month = today.getMonthValue();
       int year = today.getYear();
       String mont = "";
        switch (month) {
            case 1 -> {
                month = 12;
                year = year - 1;
            }
            
            default -> month = month - 1;
        }
        
     String  mon = String.format("%02d", month);
     String ym = year+"-"+mon;
       
       if(null != mon)switch (mon) {
            case "01" -> mont = "January";
            case "02" -> mont = "February";
            case "03" -> mont = "March";
            case "04" -> mont = "April";
            case "05" -> mont = "May";
            case "06" -> mont = "June";
            case "07" -> mont = "July";
            case "08" -> mont = "August";
            case "09" -> mont = "September";
            case "10" -> mont = "October";
            case "11" -> mont = "November";
            case "12" -> mont = "December";
            default -> {
                    }
        }

                try{ 

              JasperDesign jasdi = JRXmlLoader.load("C:\\Users\\nisal\\Documents\\NetBeansProjects\\LibraryManagementSystem\\src\\reports\\Issues.jrxml");
              String sql ="SELECT * FROM `issue` WHERE `issuedate`LIKE '%" +ym+ "%' ";
              JRDesignQuery newQuery = new JRDesignQuery();
              newQuery.setText(sql);
              jasdi.setQuery(newQuery);
              
              HashMap<String, Object> para = new HashMap<>();
              para.put("month", mont);
              JasperReport js = JasperCompileManager.compileReport(jasdi);
              JasperPrint jp = JasperFillManager.fillReport(js,para, conn);
             // JasperViewer.viewReport(jp);
              JasperViewer jv = new JasperViewer( jp, false );
              jv.viewReport( jp, false );
             }catch(Exception e){

                 JOptionPane.showMessageDialog(rootPane, e);

             }
               
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

     private void SearchMember(){
         
        try{
            String id =txtmemid.getText();
            String sql="SELECT * FROM `member` WHERE memberid= '"+id+"' && status = 'eligible'";
                   
           pst = conn.prepareStatement(sql);
           rs=pst.executeQuery();
              
            if(rs.next()){
            txtmemname.setText(rs.getString("name"));
           
        }
            else{
            JOptionPane.showMessageDialog(null, "Member Uneligible");
        }
            
            rs.close();
            pst.close();
       
       
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       
       }
    }
     
      public void SearchBook(){
         
        try{
            String id =txtisbn.getText();
            
            
           String sql="SELECT * FROM `book` WHERE isbn= '"+id+"' && type ='borrow' && status = 'available'";            
           pst = conn.prepareStatement(sql);
           rs=pst.executeQuery();
              
            if(rs.next()){
            txtbookname.setText(rs.getString("name"));
           
        }
            else{
            JOptionPane.showMessageDialog(null, "Book Unavailable");
        }
            
            rs.close();
            pst.close();
       
       
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       
       }
    }
      
      
      public void UpdateBooks(){
      
      try{
          
          String sql = "UPDATE `book` SET `status` = 'issued' WHERE isbn = '"+txtisbn.getText()+"'";
          pst=(PreparedStatement) conn.prepareStatement(sql);
          pst.execute();
          
          rs.close();
            pst.close();
           
      }catch(Exception e){
      
          JOptionPane.showMessageDialog(rootPane, e);
      }
      
  }
      
       public void UpdateMembers(){
      
      try{
          
          String sql = "UPDATE `member` SET `status` = 'borrowed' WHERE memberid = '"+txtmemid.getText()+"'";
          pst=(PreparedStatement) conn.prepareStatement(sql);
          pst.execute();
          
          rs.close();
            pst.close();
          
      }catch(Exception e){
      
          JOptionPane.showMessageDialog(rootPane, e);
      }
      
  }
       
         public void DeletedIssues(){
    
      try{
          
        
        String memberid = txtmemid.getText();
        String membername = txtmemname.getText();
        String isbn = txtisbn.getText();
        String bookname = txtbookname.getText();
        String issuedate = ((JTextField)dateissue.getDateEditor().getUiComponent()).getText();
        String duedate = ((JTextField)datedue.getDateEditor().getUiComponent()).getText();
        
        LocalDate today = LocalDate.now();

            String sql = "INSERT INTO `deletedissues`(`issueid`, `memberid`, `membername`, `isbn`, `bookname`, `issuedate`, `duedate`,`status`, `deleteddate`) VALUES((SELECT `issueid` FROM `issue` WHERE `isbn` = '"+txtisbn.getText()+"' && `memberid` = '"+txtmemid.getText()+"'),'"+memberid+"','"+membername+"','"+isbn+"','"+bookname+"','"+issuedate+"','"+duedate+"', (SELECT `status` FROM `issue` WHERE `isbn` = '"+txtisbn.getText()+"' && `memberid` = '"+txtmemid.getText()+"'), '"+today+"')";            
            pst = conn.prepareStatement(sql);
            pst.execute();
            
            rs.close();
            pst.close();
                    
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(rootPane, e);
        
        } 
    }

      

      
      
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnbookget;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnmemget;
    private javax.swing.JButton btnupdate;
    private com.toedter.calendar.JDateChooser datedue;
    private com.toedter.calendar.JDateChooser dateissue;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblissues;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtisbn;
    private javax.swing.JTextField txtmemid;
    private javax.swing.JTextField txtmemname;
    // End of variables declaration//GEN-END:variables
}
