
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nisal
 */
public class Books extends javax.swing.JInternalFrame {
    
    Connection conn ;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Books
     */
    public Books() {
        initComponents();
       // conn = JDBC.ConnectDB();
        conn = JDBC.ConnectDB();
        loadTable();
        
         this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI)this.getUI();
        bui.setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtisbn = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtauthor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        combotype = new javax.swing.JComboBox<>();
        combocategory = new javax.swing.JComboBox<>();
        txtpublisher = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbooks = new javax.swing.JTable();
        txtsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnMonthly = new javax.swing.JButton();
        btndeleted = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(898, 487));
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                formAncestorResized(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnadd.setBackground(new java.awt.Color(51, 255, 204));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnadd.setText("    Add");
        btnadd.setBorder(null);
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(255, 102, 102));
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.gif"))); // NOI18N
        btndelete.setText("  Delete");
        btndelete.setBorder(null);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(255, 255, 102));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btnupdate.setText("  Update");
        btnupdate.setBorder(null);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("ISBN");

        jLabel6.setText("Name");

        jLabel7.setText("Author");

        txtisbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtisbnActionPerformed(evt);
            }
        });

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtauthorActionPerformed(evt);
            }
        });

        jLabel8.setText("Publisher");

        jLabel14.setText("Category");

        jLabel15.setText("Price");

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });

        jLabel16.setText("Issue Type");

        combotype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "borrow", "reference" }));
        combotype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotypeActionPerformed(evt);
            }
        });

        combocategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "History", "Languages", "Advanced Level", "Ordinary Level", "Information Technology", " " }));
        combocategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocategoryActionPerformed(evt);
            }
        });

        txtpublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpublisherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtauthor, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(txtname)
                    .addComponent(txtisbn))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtpublisher))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtprice)
                            .addComponent(combocategory, 0, 112, Short.MAX_VALUE))))
                .addGap(23, 23, 23)
                .addComponent(jLabel16)
                .addGap(32, 32, 32)
                .addComponent(combotype, 0, 77, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16)
                    .addComponent(combotype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combocategory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setAutoscrolls(true);

        tblbooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblbooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbooks);

        txtsearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel2.setText("Search");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        jLabel3.setText("   Reports");

        btnMonthly.setBackground(new java.awt.Color(102, 102, 102));
        btnMonthly.setForeground(new java.awt.Color(255, 255, 255));
        btnMonthly.setText("Monthly Books");
        btnMonthly.setBorder(null);
        btnMonthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthlyActionPerformed(evt);
            }
        });

        btndeleted.setBackground(new java.awt.Color(102, 102, 102));
        btndeleted.setForeground(new java.awt.Color(255, 255, 255));
        btndeleted.setText("Deleted Books");
        btndeleted.setBorder(null);
        btndeleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMonthly, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(btndeleted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(btnMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btndeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jLabel11.setBackground(new java.awt.Color(220, 220, 220));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("BOOKS MANAGEMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtisbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtisbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtisbnActionPerformed

    private void txtauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtauthorActionPerformed

    private void combotypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combotypeActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
            
        String isbn = txtisbn.getText();
        String name = txtname.getText();
        String author = txtauthor.getText();
        String publisher = txtprice.getText();
        String category = combocategory.getSelectedItem().toString();
        String price = txtprice.getText();
        String type = combotype.getSelectedItem().toString();
        
         LocalDate today = LocalDate.now();
        
        try{
            
            if(validateFields()){
            
            String sql = "INSERT INTO `book`(`isbn`, `name`, `author`, `publisher`, `category`, `price`, `type`, `status`,`date`) VALUES('"+isbn+"','"+name+"','"+author+"','"+publisher+"','"+category+"','"+price+"','"+type+"','available','"+today+"')";
            pst = conn.prepareStatement(sql);
            pst.execute();
            
            rs.close();
            pst.close();
            
            JOptionPane.showMessageDialog(rootPane, "Book Added Successfully!");
            }
        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(rootPane, e);
        
        }
      
       loadTable();
            
    }//GEN-LAST:event_btnaddActionPerformed

    private void loadTable(){
    
        try{
        
            String sql ="SELECT `isbn`, `name`, `author`, `publisher`, `category`, `price`, `type`, `status` FROM `book`";
            pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblbooks.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
            rs.close();
            pst.close();
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(rootPane, e);
        
        }
    }  
  
    
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try{
            
            DeletedBooks();
            
            String sql ="DELETE FROM `book` WHERE isbn ='"+txtisbn.getText()+"'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            
            rs.close();
            pst.close();
            
            JOptionPane.showMessageDialog(rootPane, "Successfully Deleted");
            loadTable();
            
        }catch(Exception e){
        
           JOptionPane.showMessageDialog(rootPane, e);

        } 
        
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tblbooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbooksMouseClicked

        
        DefaultTableModel tmodel = (DefaultTableModel)tblbooks.getModel();
        int selectrowindex = tblbooks.getSelectedRow();
        txtisbn.setText(tmodel.getValueAt(selectrowindex, 0).toString());
        txtname.setText(tmodel.getValueAt(selectrowindex, 1).toString());
        txtauthor.setText(tmodel.getValueAt(selectrowindex, 2).toString());
        txtpublisher.setText(tmodel.getValueAt(selectrowindex, 3).toString());
        combocategory.setSelectedItem(tmodel.getValueAt(selectrowindex, 4).toString());
        txtprice.setText(tmodel.getValueAt(selectrowindex, 5).toString());
        combotype.setSelectedItem(tmodel.getValueAt(selectrowindex, 6).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_tblbooksMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        
        String isbn = txtisbn.getText();
        String name = txtname.getText();
        String author = txtauthor.getText();
        String publisher = txtprice.getText();
        String category = combocategory.getSelectedItem().toString();
        String price = txtprice.getText();
        String type = combotype.getSelectedItem().toString();
        
        
        try{
            
            
            String sql = "UPDATE `book` SET `name`='"+name+"',`author`='"+author+"',`publisher`='"+publisher+"',`category`='"+category+"',`price`='"+price+"',`type`='"+type+"' WHERE isbn = '"+isbn+"'";
            pst =conn.prepareStatement(sql);
            pst.execute();
            
            rs.close();
            pst.close();
            
            JOptionPane.showMessageDialog(rootPane, "Successfully Updated");
            loadTable();
            
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(rootPane, e);

        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void combocategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combocategoryActionPerformed

    private void formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorResized

        int a =  evt.getChanged().getWidth();
       int b = evt.getChanged().getHeight();
       this.setSize(a, b);
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorResized

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        
        String search = txtsearch.getText();
        
                try {

                        String sql = "SELECT `isbn`, `name`, `author`, `publisher`, `category`, `price`, `type`, `status` FROM `book` WHERE `name` LIKE '%" + search + "%' "
                            + "OR `isbn` LIKE '%"+search+"%' OR `author` LIKE '%"+search+"%'";
                        
                        pst = conn.prepareStatement(sql);
                         rs=pst.executeQuery();
                         tblbooks.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
                         
                         rs.close();
                         pst.close();
                                             
            } catch (Exception e) {
                   
                    JOptionPane.showMessageDialog(null, e);
                
                      
          } 
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtpublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpublisherActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void btnMonthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthlyActionPerformed
        
        
        
             LocalDate today = LocalDate.now();
        
       int month = today.getMonthValue();
       int year = today.getYear();
       String mont = "";
        switch (month) {
            case 1 -> {
                month = 12;
                year = year - 1;
            }
            
            default -> month = month - 1;
        }
        
     String  mon = String.format("%02d", month);
     String ym = year+"-"+mon;
       
       if(null != mon)switch (mon) {
            case "01" -> mont = "January";
            case "02" -> mont = "February";
            case "03" -> mont = "March";
            case "04" -> mont = "April";
            case "05" -> mont = "May";
            case "06" -> mont = "June";
            case "07" -> mont = "July";
            case "08" -> mont = "August";
            case "09" -> mont = "September";
            case "10" -> mont = "October";
            case "11" -> mont = "November";
            case "12" -> mont = "December";
            default -> {
                    }
        }

                try{ 

              JasperDesign jasdi = JRXmlLoader.load("C:\\Users\\nisal\\Documents\\NetBeansProjects\\LibraryManagementSystem\\src\\reports\\MonthlyBooks.jrxml");
              String sql ="SELECT * FROM `book` WHERE `date`LIKE '%" +ym+ "%' ";
              JRDesignQuery newQuery = new JRDesignQuery();
              newQuery.setText(sql);
              jasdi.setQuery(newQuery);
              
              HashMap<String, Object> para = new HashMap<>();
              para.put("month", mont);
              JasperReport js = JasperCompileManager.compileReport(jasdi);
              JasperPrint jp = JasperFillManager.fillReport(js,para, conn);
             // JasperViewer.viewReport(jp);
              JasperViewer jv = new JasperViewer( jp, false );
              jv.viewReport( jp, false );
             }catch(Exception e){

                 JOptionPane.showMessageDialog(rootPane, e);

             }
               
        
        
        
        
        
    }//GEN-LAST:event_btnMonthlyActionPerformed

    private void btndeletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletedActionPerformed

                try{ 

              JasperDesign jasdi = JRXmlLoader.load("C:\\Users\\nisal\\Documents\\NetBeansProjects\\LibraryManagementSystem\\src\\reports\\DeletedBooks.jrxml");
              String sql ="SELECT * FROM `deletedbooks`";
              JRDesignQuery newQuery = new JRDesignQuery();
              newQuery.setText(sql);
              jasdi.setQuery(newQuery);
              
              HashMap<String, Object> para = new HashMap<>();
              JasperReport js = JasperCompileManager.compileReport(jasdi);
              JasperPrint jp = JasperFillManager.fillReport(js,para, conn);
             // JasperViewer.viewReport(jp);
              JasperViewer jv = new JasperViewer( jp, false );
              jv.viewReport( jp, false );
             }catch(Exception e){

                 JOptionPane.showMessageDialog(rootPane, e);

             }



        // TODO add your handling code here:
    }//GEN-LAST:event_btndeletedActionPerformed

      private void DeletedBooks(){
    
      try{
          
         String isbn = txtisbn.getText();
        String name = txtname.getText();
        String author = txtauthor.getText();
        String publisher = txtprice.getText();
        String category = combocategory.getSelectedItem().toString();
        String price = txtprice.getText();
        String type = combotype.getSelectedItem().toString();
        
        LocalDate today = LocalDate.now();

            String sql = "INSERT INTO `deletedbooks`(`isbn`, `name`, `author`, `publisher`, `category`, `price`, `type`, `status`, `deleteddate`) VALUES('"+isbn+"','"+name+"','"+author+"','"+publisher+"','"+category+"','"+price+"','"+type+"', (SELECT `status` FROM `book` WHERE isbn ='"+txtisbn.getText()+"'), '"+today+"')";
            pst = conn.prepareStatement(sql);
            pst.execute();
            
            rs.close();
            pst.close();
                    
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(rootPane, e);
        
        } 
    }
      
     public boolean validateFields(){
        
      
        String vauthor = "[a-z A-Z]+\\.?";
        String vpublisher = "[a-z A-Z]+\\.?";
        String vprice = "[0-9,.]+\\.?";
        String vname = "[a-z A-Z]+\\.?";
        String visbn = "^[0-9]{4}$";

       
        Pattern pauthor = Pattern.compile(vauthor,  Pattern.CASE_INSENSITIVE); // start , combination , total num
        Matcher au = pauthor.matcher(txtauthor.getText());
        
        Pattern ppublisher = Pattern.compile(vpublisher, Pattern.CASE_INSENSITIVE); // start , combination , total num
        Matcher pu = ppublisher.matcher(txtpublisher.getText());

        Pattern pprice = Pattern.compile(vprice, Pattern.CASE_INSENSITIVE);
        Matcher pr = pprice.matcher(txtprice.getText());
        
        Pattern pname = Pattern.compile(vname, Pattern.CASE_INSENSITIVE);
        Matcher na = pname.matcher(txtname.getText());
        
        Pattern pisbn = Pattern.compile(visbn, Pattern.CASE_INSENSITIVE);
        Matcher is = pisbn.matcher(txtisbn.getText());
        
        
        if (txtisbn.getText().equalsIgnoreCase("")){
            
            JOptionPane.showMessageDialog(null, "Enter ISBN ");
            return false;
            
        } else{
            if (is.matches()) 
            {
                //return true;
            } else 
            {
                JOptionPane.showMessageDialog(null, "ISBN invalid ");
                return false;
            }
        
        }
        if (txtname.getText().equalsIgnoreCase("")){
            
            JOptionPane.showMessageDialog(null, "Enter Name ");
            return false;
            
        } else{
            if (na.matches()) 
            {
                //return true;
            } else 
            {
                JOptionPane.showMessageDialog(null, "Name invalid ");
                return false;
            }
        
        }         if (txtauthor.getText().equalsIgnoreCase("")){
            
            JOptionPane.showMessageDialog(null, "Enter Author ");
            return false;
            
        } else{
            if (au.matches()) 
            {
                //return true;
            } else 
            {
                JOptionPane.showMessageDialog(null, "Author invalid ");
                return false;
            }
        
        }
         if (txtpublisher.getText().equalsIgnoreCase("")){
            
            JOptionPane.showMessageDialog(null, "Enter Publisher ");
            return false;
            
        } else{
            if (pu.matches()) 
            {
                //return true;
            } else 
            {
                JOptionPane.showMessageDialog(null, "Publisher invalid ");
                return false;
            }
         if (combocategory.getSelectedItem().toString().equalsIgnoreCase("Select")){
            
            JOptionPane.showMessageDialog(null, "Enter Category ");
            return false;
        }
        }
         if (txtprice.getText().equalsIgnoreCase("")){
            
            JOptionPane.showMessageDialog(null, "Enter Price ");
            return false;
            
        } else{
            if (pr.matches()) 
            {
                //return true;
            } else 
            {
                JOptionPane.showMessageDialog(null, "Price invalid ");
                return false;
            }
        
        }
                  if (combotype.getSelectedItem().toString().equalsIgnoreCase("Select")){
            
            JOptionPane.showMessageDialog(null, "Enter Category ");
            return false;
        }
              
       return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMonthly;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndeleted;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> combocategory;
    private javax.swing.JComboBox<String> combotype;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbooks;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JTextField txtisbn;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtpublisher;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
