
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nisal
 */
public class Returns extends javax.swing.JInternalFrame {
    
    Connection conn ;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Books
     */
    public Returns() {
        initComponents();
        conn = JDBC.ConnectDB();
        
         this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI)this.getUI();
        bui.setNorthPane(null);
        
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmemid = new javax.swing.JTextField();
        txtisbn = new javax.swing.JTextField();
        btnget = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtmemname = new javax.swing.JTextField();
        txtbookname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtissuedate = new javax.swing.JTextField();
        txtduedate = new javax.swing.JTextField();
        txtissueid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblreturns = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        datereturn = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        btncalculate = new javax.swing.JButton();
        txtfine = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(898, 487));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnadd.setText("Return");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(btnupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Member ID");

        jLabel3.setText("ISBN");

        txtmemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmemidActionPerformed(evt);
            }
        });
        txtmemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmemidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmemidKeyReleased(evt);
            }
        });

        txtisbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtisbnActionPerformed(evt);
            }
        });

        btnget.setText("Get");
        btnget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngetActionPerformed(evt);
            }
        });

        jLabel1.setText("Member Name");

        txtmemname.setEditable(false);
        txtmemname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmemnameActionPerformed(evt);
            }
        });

        txtbookname.setEditable(false);
        txtbookname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbooknameActionPerformed(evt);
            }
        });

        jLabel4.setText("Book Name");

        jLabel5.setText("Issue Date");

        jLabel6.setText("Due Date");

        txtissuedate.setEditable(false);

        txtduedate.setEditable(false);

        txtissueid.setEditable(false);

        jLabel7.setText("Isssue ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(181, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtduedate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(txtissuedate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmemid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbookname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmemname, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(49, 49, 49))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtissueid)
                                        .addContainerGap())
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnget)
                                        .addGap(0, 0, Short.MAX_VALUE))))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtmemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnget))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtisbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtmemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtbookname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtissueid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel7)))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtissuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtduedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setAutoscrolls(true);

        tblreturns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblreturns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblreturnsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblreturns);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Return Date");

        btncalculate.setText("Calculate");
        btncalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculateActionPerformed(evt);
            }
        });

        txtfine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfineActionPerformed(evt);
            }
        });

        jLabel9.setText("Fine");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(datereturn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btncalculate))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31)
                        .addComponent(txtfine, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncalculate)
                    .addComponent(jLabel8)
                    .addComponent(datereturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtfine, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
            
    
        String memberid = txtmemid.getText();
        String membername = txtmemname.getText();
        String isbn = txtisbn.getText();
        String bookname = txtbookname.getText();
        String issuedate = txtissuedate.getText();
        String duedate = txtduedate.getText();
        String issueid = txtissueid.getText();
        String fine = txtfine.getText();
        String returndate = ((JTextField)datereturn.getDateEditor().getUiComponent()).getText();

        try{
            
            String sql = "INSERT INTO `return`(`issueid`, `memberid`, `membername`, `isbn`, `bookname`, `issuedate`, `duedate`,`returndate` , `fine`) VALUES('"+issueid+"','"+memberid+"','"+membername+"','"+isbn+"','"+bookname+"','"+issuedate+"','"+duedate+"','"+returndate+"','"+fine+"')";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(rootPane, "Book Retured Successfully!");

        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(rootPane, e);
        
        }
       UpdateMembers();
       UpdateBooks();
       UpdateIssues();
       loadTable();
            
    }//GEN-LAST:event_btnaddActionPerformed

    private void loadTable(){
    
        try{
        
            String sql ="SELECT `returnid`, `issueid`, `memberid`, `membername`, `isbn`, `bookname`, `issuedate`, `duedate` , `returndate` , `fine` FROM `return`";
            pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblreturns.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(rootPane, e);
        
        }
    }  
  
    
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try{
            
            DeletedReturns();
            
            String sql ="DELETE FROM `return` WHERE issueid ='"+txtissueid.getText()+"'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(rootPane, "Successfully Deleted");
            loadTable();
            
        }catch(Exception e){
        
           JOptionPane.showMessageDialog(rootPane, e);

        } 
        
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tblreturnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblreturnsMouseClicked

        
        DefaultTableModel tmodel = (DefaultTableModel)tblreturns.getModel();
        int selectrowindex = tblreturns.getSelectedRow();
     
        txtmemid.setText(tmodel.getValueAt(selectrowindex, 2).toString());
        txtisbn.setText(tmodel.getValueAt(selectrowindex, 4).toString());
        txtmemname.setText(tmodel.getValueAt(selectrowindex, 3).toString());
        txtbookname.setText(tmodel.getValueAt(selectrowindex, 5).toString());
        txtissuedate.setText(tmodel.getValueAt(selectrowindex, 6).toString());
        txtduedate.setText(tmodel.getValueAt(selectrowindex, 7).toString());
        txtissueid.setText(tmodel.getValueAt(selectrowindex, 1).toString());
        ((JTextField)datereturn.getDateEditor().getUiComponent()).setText(tmodel.getValueAt(selectrowindex, 8).toString());
        txtfine.setText(tmodel.getValueAt(selectrowindex, 9).toString());
       
   
        // TODO add your handling code here:
    }//GEN-LAST:event_tblreturnsMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
      
        String fine = txtfine.getText();
        String returndate = ((JTextField)datereturn.getDateEditor().getUiComponent()).getText();
        
        try{
            
            
            String sql = "UPDATE `return` SET `returndate`='"+returndate+"',`fine`='"+fine+"' WHERE issueid ='"+txtissueid.getText()+"'";
            pst =conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Successfully Updated");
            loadTable();
            
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(rootPane, e);

        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtmemidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmemidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmemidKeyReleased

    private void txtmemidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmemidKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtmemidKeyPressed

    private void txtmemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmemidActionPerformed

    private void txtisbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtisbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtisbnActionPerformed

    private void btngetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngetActionPerformed
        // TODO add your handling code here:        
        GetDetails();
    }//GEN-LAST:event_btngetActionPerformed

    private void txtbooknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbooknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbooknameActionPerformed

    private void txtmemnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmemnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmemnameActionPerformed

    private void btncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncalculateActionPerformed

    private void txtfineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfineActionPerformed

     public void GetDetails(){
         
        try{
            String id =txtmemid.getText();
            String is = txtisbn.getText();
            
            String sql="SELECT * FROM `issue` WHERE memberid= '"+id+"' && isbn = '"+is+"'" ;
                   
           pst = conn.prepareStatement(sql);
           rs=pst.executeQuery();
              
            if(rs.next()){
            txtmemname.setText(rs.getString("membername"));
            txtbookname.setText(rs.getString("bookname"));
            txtissuedate.setText(rs.getString("issuedate"));
            txtduedate.setText(rs.getString("duedate"));
            txtissueid.setText(rs.getString("issueid"));
        }
            else{
            JOptionPane.showMessageDialog(null, "Incorrect Details");
        }
       
       
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       
       }
    }
     
       private void UpdateBooks(){
      
      try{
          
          String sql = "UPDATE `book` SET `status` = 'available' WHERE isbn = '"+txtisbn.getText()+"'";
          pst=(PreparedStatement) conn.prepareStatement(sql);
          pst.execute();
          
         
            loadTable();
      
      
      }catch(Exception e){
      
          JOptionPane.showMessageDialog(rootPane, e);
      }
      
      }
      
       private void UpdateMembers(){
      
      try{
          
          String sql = "UPDATE `member` SET `status` = 'eligible' WHERE memberid = '"+txtmemid.getText()+"'";
          pst=(PreparedStatement) conn.prepareStatement(sql);
          pst.execute();
          
          
            loadTable();
      
      
      }catch(Exception e){
      
          JOptionPane.showMessageDialog(rootPane, e);
      }
      
      }
       
          private void UpdateIssues(){
      
      try{
          
          String sql = "UPDATE `issue` SET `status` = 'returned' WHERE issueid = '"+txtissueid.getText()+"'";
          pst=(PreparedStatement) conn.prepareStatement(sql);
          pst.execute();
          
          
            loadTable();
      
      
      }catch(Exception e){
      
          JOptionPane.showMessageDialog(rootPane, e);
      }
      
      }
          
          
      private void DeletedReturns(){
    
      try{
          
       
        String memberid = txtmemid.getText();
        String membername = txtmemname.getText();
        String isbn = txtisbn.getText();
        String bookname = txtbookname.getText();
        String issuedate = txtissuedate.getText();
        String duedate = txtduedate.getText();
        String issueid = txtissueid.getText();
        String fine = txtfine.getText();
        String returndate = ((JTextField)datereturn.getDateEditor().getUiComponent()).getText();
        
        LocalDate today = LocalDate.now();

            String sql = "INSERT INTO `deletedreturns`(`returnid`, `issueid`, `memberid`, `membername`, `isbn`, `bookname`, `issuedate`, `duedate`,`returndate` , `fine`, `deleteddate`) VALUES((SELECT `returnid` FROM `return` WHERE `issueid` = '"+issueid+"'),'"+issueid+"','"+memberid+"','"+membername+"','"+isbn+"','"+bookname+"','"+issuedate+"','"+duedate+"','"+returndate+"','"+fine+"','"+today+"')";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
                    
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(rootPane, e);
        
        } 
    }

    
      

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncalculate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnget;
    private javax.swing.JButton btnupdate;
    private com.toedter.calendar.JDateChooser datereturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblreturns;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtduedate;
    private javax.swing.JTextField txtfine;
    private javax.swing.JTextField txtisbn;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtissueid;
    private javax.swing.JTextField txtmemid;
    private javax.swing.JTextField txtmemname;
    // End of variables declaration//GEN-END:variables
}
